/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaz;

import com.negocio.GestionEmpleados;
import com.utilidades.UtilidadesValidacion;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CEC
 */
public class ConsultaEmpleadosInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaEmpleados
     */
    public ConsultaEmpleadosInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cedulaTextField = new javax.swing.JTextField();
        nombresTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidosTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleadosTable = new javax.swing.JTable();
        buscarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Búsqueda de empleados");

        jLabel2.setText("Cédula:");

        cedulaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaTextFieldKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellidos:");

        listaEmpleadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listaEmpleadosTable);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1)
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidosTextField)
                            .addComponent(cedulaTextField)
                            .addComponent(nombresTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cedulaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarButton)
                    .addComponent(salirButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Map<String, String> buscarParametro() {
        String valorParametro = "";

        Map<String, String> map = new HashMap<String, String>();

        map.put("parametro", "");
        map.put("valorParametro", "");

        if (cedulaTextField.getText().isEmpty() == false) {
            valorParametro = "c";
            map.put("parametro", "c");
            map.put("valorParametro", cedulaTextField.getText());
        } else {
            if (nombresTextField.getText().isEmpty() == false) {
                valorParametro = "n";
                map.put("parametro", "n");
                map.put("valorParametro", nombresTextField.getText());
            } else {
                if (apellidosTextField.getText().isEmpty() == false) {
                    valorParametro = "a";
                    map.put("parametro", "a");
                    map.put("valorParametro", apellidosTextField.getText());
                }
            }
        }
        return map;
    }

    public DefaultTableModel llenarTabla(ResultSet resultadoConsulta) throws SQLException {
        DefaultTableModel defaultTableModel = new DefaultTableModel();

        defaultTableModel.setColumnCount(0);
        defaultTableModel.addColumn("Identificaion");
        defaultTableModel.addColumn("Nombres");
        defaultTableModel.addColumn("Apellidos");
        defaultTableModel.addColumn("Correo");
        defaultTableModel.addColumn("Cargo");
        
        resultadoConsulta.last();
        defaultTableModel.setNumRows(resultadoConsulta.getRow());
        resultadoConsulta.beforeFirst();
        int fila = 0;
        while (resultadoConsulta.next()) {
            String value = resultadoConsulta.getString("emp_identificacion");
            defaultTableModel.setValueAt(value, fila, 0);
            value = resultadoConsulta.getString("emp_nombre");
            defaultTableModel.setValueAt(value, fila, 1);
            value = resultadoConsulta.getString("emp_apellidos");
            defaultTableModel.setValueAt(value, fila, 2);
            value = resultadoConsulta.getString("emp_correo");
            defaultTableModel.setValueAt(value, fila, 3);
            value = resultadoConsulta.getString("emp_cargo");
            defaultTableModel.setValueAt(value, fila, 4);
            fila++;
        }
        
        return defaultTableModel;
    }

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:

        try {
            Map<String, String> map = buscarParametro();
            String nombreParametro = map.get("parametro");
            String valorParametro = map.get("valorParametro");
            ResultSet busquedaEmpleado;
            if (nombreParametro.length() > 0) {
               
                String[] argumentos = new String[1];
                argumentos[0] = valorParametro;
                busquedaEmpleado = GestionEmpleados.invocarProcedimientoBusqueda(nombreParametro, argumentos);
                
                  busquedaEmpleado.last();
            int size = busquedaEmpleado.getRow();
            System.out.println("sizebusquedaEmpleado"+size);
            busquedaEmpleado.beforeFirst();
                
                DefaultTableModel defaultTableModel=this.llenarTabla(busquedaEmpleado);
                this.listaEmpleadosTable.setModel(defaultTableModel);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un campo");
            }

        } catch (Exception ex) {
            System.err.println("Ocurrió un error: " + ex.getLocalizedMessage());
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: " + ex.getLocalizedMessage());

//            StringWriter stringWriter = new StringWriter();
//            PrintWriter printWriter = new PrintWriter(stringWriter);
//            ex.printStackTrace(printWriter);
//            String stackError=stringWriter.toString().substring(0, 150);
//            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: "+stackError);
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void cedulaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaTextFieldKeyTyped
        // TODO add your handling code here:
        System.out.println(String.valueOf(evt.getKeyChar()));
        boolean soloNumeros=UtilidadesValidacion.validarSoloNumeros(this.cedulaTextField.getText()+String.valueOf(evt.getKeyChar()));
        
        if (soloNumeros==false) {
            evt.consume();
        }
    }//GEN-LAST:event_cedulaTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField cedulaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaEmpleadosTable;
    private javax.swing.JTextField nombresTextField;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
