/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaz;

import com.negocio.GestionEmpleados;
import com.utilidades.UtilidadesValidacion;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author CEC
 */
public class IngresarEmpleadoInternalFrame extends javax.swing.JInternalFrame {

    public boolean estaActualizando;
    
    /**
     * Creates new form IngresarEmpleadoInternalFrame
     */
    public IngresarEmpleadoInternalFrame(boolean estaActualizando) {
        initComponents();
        this.estaActualizando=estaActualizando;
        if (this.estaActualizando==true) {
            this.titleLabel.setText("Actualizar");
            this.ingrearEmpleadoButton.setLabel("Actualizar");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        identificacionTextField = new java.awt.TextField();
        nombresTextField = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        apellidosTextField = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        direccionTextField = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoTextField = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        celularTextField = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        correoTextField = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ingrearEmpleadoButton = new java.awt.Button();
        titleLabel = new javax.swing.JLabel();
        cargoComboBox = new javax.swing.JComboBox();
        salirButton = new javax.swing.JButton();

        jLabel1.setText("Identificación: ");

        identificacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres: ");

        jLabel3.setText("Apellidos: ");

        jLabel4.setText("Dirección:");

        telefonoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Celular:");

        jLabel7.setText("Correo:");

        jLabel8.setText("Cargo:");

        ingrearEmpleadoButton.setLabel("Ingresar");
        ingrearEmpleadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingrearEmpleadoButtonActionPerformed(evt);
            }
        });

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Ingreso de empleado");

        cargoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Director", "Gerente", "Subgerente", "Secretaria", "Desarrollador", " " }));

        salirButton.setText("Cerrar");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(titleLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombresTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(apellidosTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(identificacionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                .addComponent(direccionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(celularTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telefonoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(correoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cargoComboBox, 0, 357, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(ingrearEmpleadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(salirButton)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salirButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identificacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cargoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingrearEmpleadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCamposIngresoEmpleadoCorrectos() {

        boolean camposCorrectos = true;

        if (UtilidadesValidacion.validarSoloNumeros(this.identificacionTextField.getText()) == false) {
            return camposCorrectos = false;
        }
//        if (UtilidadesValidacion.validarSoloLetras(this.nombresTextField.getText()) == false) {
//            return camposCorrectos = false;
//        }
//        if (UtilidadesValidacion.validarSoloLetras(this.apellidosTextField.getText()) == false) {
//            return camposCorrectos = false;
//        }
        if (UtilidadesValidacion.validarSoloNumeros(this.telefonoTextField.getText()) == false) {
            return camposCorrectos = false;
        }
        if (UtilidadesValidacion.validarSoloNumeros(this.celularTextField.getText()) == false) {
            return camposCorrectos = false;
        }
        if (UtilidadesValidacion.validarCorreoElectronico(this.correoTextField.getText()) == false) {
            return camposCorrectos = false;
        }

        return camposCorrectos;
    }

    private void ingrearEmpleadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingrearEmpleadoButtonActionPerformed
        // TODO add your handling code here:

        boolean camposCorrectos = this.validarCamposIngresoEmpleadoCorrectos();

        if (camposCorrectos == true) {
            String[] argumentos = new String[8];
            argumentos[0] = this.identificacionTextField.getText();
            argumentos[1] = this.nombresTextField.getText();
            argumentos[2] = this.apellidosTextField.getText();
            argumentos[3] = this.direccionTextField.getText();
            argumentos[4] = this.telefonoTextField.getText();
            argumentos[5] = this.celularTextField.getText();
            argumentos[6] = this.correoTextField.getText();
            argumentos[7] = (String) this.cargoComboBox.getSelectedItem();

            try {
                
                if (this.estaActualizando==true) {
                    GestionEmpleados.actualizarEmpleado(argumentos);
                     JOptionPane.showMessageDialog(rootPane, "Empleado actualizado");
                }
                else{
                    GestionEmpleados.ingresarEmpleado(argumentos);
                     JOptionPane.showMessageDialog(rootPane, "Empleado ingresado");
                }
            } catch (IOException | SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                System.err.println("Ocurrió un error: " + ex.getLocalizedMessage());
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: " + ex.getLocalizedMessage());
            } catch (Exception ex) {
                System.err.println("Ocurrió un error: " + ex.getLocalizedMessage());
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: " + ex.getLocalizedMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Por favor ingreso los datos correctamente");
        }


    }//GEN-LAST:event_ingrearEmpleadoButtonActionPerformed

    private void identificacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTextFieldActionPerformed

    private void telefonoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextFieldActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField apellidosTextField;
    private javax.swing.JComboBox cargoComboBox;
    private java.awt.TextField celularTextField;
    private java.awt.TextField correoTextField;
    private java.awt.TextField direccionTextField;
    private java.awt.TextField identificacionTextField;
    private java.awt.Button ingrearEmpleadoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.TextField nombresTextField;
    private javax.swing.JButton salirButton;
    private java.awt.TextField telefonoTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
