/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaz;

import java.io.PrintWriter;
import java.io.StringWriter;
import javax.lang.model.type.PrimitiveType;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.xml.bind.PropertyException;

/**
 *
 * @author CEC
 */
public class Principal extends javax.swing.JFrame {

    
    private JInternalFrame previusInternalFrame;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        salirMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        consultaEmpleadosMenuItem = new javax.swing.JMenuItem();
        ingresoEmpleadoMenuItem = new javax.swing.JMenuItem();
        editarEmpleadoMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Inicio");
        jMenu3.setToolTipText("Click para ver");

        salirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        salirMenuItem.setText("Salir");
        salirMenuItem.setToolTipText("Permite salir del sistema");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(salirMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Empleados");

        consultaEmpleadosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        consultaEmpleadosMenuItem.setText("Consulta empleados");
        consultaEmpleadosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEmpleadosMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(consultaEmpleadosMenuItem);

        ingresoEmpleadoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        ingresoEmpleadoMenuItem.setText("Ingreso Empleado");
        ingresoEmpleadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoEmpleadoMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(ingresoEmpleadoMenuItem);

        editarEmpleadoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        editarEmpleadoMenuItem.setText("Editar empleado");
        editarEmpleadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadoMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(editarEmpleadoMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Clientes");

        jMenuItem7.setText("Carga masiva clientes");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Proveedores");

        jMenuItem5.setText("Consultar proveedor");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Ingreso proveedor");
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Procesos");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ayuda");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void consultaEmpleadosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEmpleadosMenuItemActionPerformed
        // TODO add your handling code here:
        if(previusInternalFrame !=null) {//make sure its not null
           previusInternalFrame.dispose();//close the previos internalframe
       }
        
        ConsultaEmpleadosInternalFrame consultaEmpleadosInternalFrame = new ConsultaEmpleadosInternalFrame();
        previusInternalFrame=consultaEmpleadosInternalFrame;
        
        this.add(consultaEmpleadosInternalFrame);
        consultaEmpleadosInternalFrame.show();
        try {
            consultaEmpleadosInternalFrame.setMaximum(true);
        } catch (Exception ex) {
            System.err.println("Ocurrió un error: " + ex.getLocalizedMessage());
            ex.printStackTrace();

            StringWriter stringWriter = new StringWriter();
            PrintWriter printWriter = new PrintWriter(stringWriter);
            ex.printStackTrace(printWriter);
            String stackError = stringWriter.toString().substring(0, 150);
            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: " + stackError);
        }


    }//GEN-LAST:event_consultaEmpleadosMenuItemActionPerformed

    private void ingresoEmpleadoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoEmpleadoMenuItemActionPerformed
        // TODO add your handling code here:
        
        if (previusInternalFrame != null) {//make sure its not null
            previusInternalFrame.dispose();//close the previos internalframe
        }
        
        IngresarEmpleadoInternalFrame ingresarEmpleadoInternalFrame = new IngresarEmpleadoInternalFrame(false);
        previusInternalFrame=ingresarEmpleadoInternalFrame;
        
        this.add(ingresarEmpleadoInternalFrame);
        ingresarEmpleadoInternalFrame.show();
        try {
            ingresarEmpleadoInternalFrame.setMaximum(true);
        } catch (Exception ex) {
            System.err.println("Ocurrió un error: " + ex.getLocalizedMessage());
            ex.printStackTrace();

            StringWriter stringWriter = new StringWriter();
            PrintWriter printWriter = new PrintWriter(stringWriter);
            ex.printStackTrace(printWriter);
            String stackError = stringWriter.toString().substring(0, 150);
            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: " + stackError);
        }

    }//GEN-LAST:event_ingresoEmpleadoMenuItemActionPerformed

    private void editarEmpleadoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoMenuItemActionPerformed
        // TODO add your handling code here:
//         if(previusInternalFrame !=null) {//make sure its not null
//           previusInternalFrame.dispose();//close the previos internalframe
//       }
//        
//        ActualizarEmpleadoInternalFrame actualizarEmpleadoInternalFrame = new ActualizarEmpleadoInternalFrame();
//        previusInternalFrame=actualizarEmpleadoInternalFrame;
//        
//        this.add(actualizarEmpleadoInternalFrame);
//        actualizarEmpleadoInternalFrame.show();
//        try {
//            actualizarEmpleadoInternalFrame.setMaximum(true);
//        } catch (Exception ex) {
//            System.err.println("Ocurrió un error: " + ex.getLocalizedMessage());
//            ex.printStackTrace();
//
//            StringWriter stringWriter = new StringWriter();
//            PrintWriter printWriter = new PrintWriter(stringWriter);
//            ex.printStackTrace(printWriter);
//            String stackError = stringWriter.toString().substring(0, 150);
//            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: " + stackError);
//        }
        
        if (previusInternalFrame != null) {//make sure its not null
            previusInternalFrame.dispose();//close the previos internalframe
        }
        
        IngresarEmpleadoInternalFrame ingresarEmpleadoInternalFrame = new IngresarEmpleadoInternalFrame(true);
        previusInternalFrame=ingresarEmpleadoInternalFrame;
        
        this.add(ingresarEmpleadoInternalFrame);
        ingresarEmpleadoInternalFrame.show();
        try {
            ingresarEmpleadoInternalFrame.setMaximum(true);
        } catch (Exception ex) {
            System.err.println("Ocurrió un error: " + ex.getLocalizedMessage());
            ex.printStackTrace();

            StringWriter stringWriter = new StringWriter();
            PrintWriter printWriter = new PrintWriter(stringWriter);
            ex.printStackTrace(printWriter);
            String stackError = stringWriter.toString().substring(0, 150);
            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error: " + stackError);
        }
        
    }//GEN-LAST:event_editarEmpleadoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultaEmpleadosMenuItem;
    private javax.swing.JMenuItem editarEmpleadoMenuItem;
    private javax.swing.JMenuItem ingresoEmpleadoMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables
}
